AWS_ACCESS_KEY_ID = 'AKIAVRUVVSYZQMLU44M4'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'trademyspin-dev'
AWS_S3_REGION_NAME = 'eu-north-1'

EMAIL_HOST_USER = 'ari@trademyspin.com'
EMAIL_HOST_PASSWORD = 'Josejose1!'

# EMAIL_HOST_USER = 'sales@click2connect.pro'
# EMAIL_HOST_PASSWORD = 'mAM7GLm!@KVTtz7'

STRIPE_SECRET_KEY = 'sk_test_51PGBE0Ci4mI52FHuWU01tfqtqNFRd1cMb3nFKZTAPOQRfCDzthYurE29J9y7L5KH8TItm1YPcfpNPanRtatk2tHA00VajSCIVi'
# STRIPE_SECRET_KEY = 'sk_test_51PGBE0Ci4mI52FHufySY3hMMzT4VGwzVKDtRejF3dDDCoBDOJ0sh9pW7BOrq957iLh1LLEK3MSRwZts4xXItKxVe00tL21v1hf'
