AWS_ACCESS_KEY_ID = 'AKIAVRUVVSYZQMLU44M4'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'trademyspin-dev'
AWS_S3_REGION_NAME = 'eu-north-1'

EMAIL_HOST_USER = 'ari@trademyspin.com'
EMAIL_HOST_PASSWORD = 'Josejose1!'

# EMAIL_HOST_USER = 'sales@click2connect.pro'
# EMAIL_HOST_PASSWORD = 'mAM7GLm!@KVTtz7'

STRIPE_SECRET_KEY = 'sk_test_51QM8CZCdnYheM7pM1YFqOPOVKgFrYZqG5JaxSTSYSbD5BQvMGJIZWJR9fYfUb475tzpexbVuWpHdlROBaL14nyyU007Q4xmj2s'
STRIPE_PUBLISHABLE_KEY = 'pk_live_51QM8CZCdnYheM7pMMYEoQ989RK4I8u4S6SX4XvvIGhu9LHekWidjvEfLL1UaMCu2131UQDkwZ2mwKcjvSc4PimeR00inHacfuR'
