# Generated by Django 4.1.7 on 2024-05-11 09:12

from django.db import migrations, models
import rest.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='asking_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=rest.models.customer_image_upload_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bike_condition',
            field=models.CharField(blank=True, choices=[('Needs some love', 'Needs some love'), ('Works well (201-500 Rides)', 'Works well (201-500 Rides)'), ('Very good (51-200 Rides)', 'Very good (51-200 Rides)'), ('Excellent (0 - 50 Rides)', 'Excellent (0 - 50 Rides)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='buy_date',
            field=models.CharField(blank=True, choices=[('Before 2018', 'Before 2018'), ('2018 - 2020', '2018 - 2020'), ('2021 - 2022', '2021 - 2022'), ('2023 to present', '2023 to present')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending Pickup', 'Pending Pickup'), ('Pending Delivery', 'Pending Delivery'), ('Delivered', 'Delivered'), ('Sold', 'Sold')], default='Approved', max_length=20),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_email', models.EmailField(max_length=254)),
                ('seller_phone_number', models.CharField(max_length=20)),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('listings', models.ManyToManyField(related_name='transactions', to='rest.listing')),
            ],
        ),
    ]
