# Generated by Django 4.1.7 on 2024-04-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='buy_date',
            field=models.CharField(blank=True, choices=[('Before 2018', 'Before 2018'), ('2018 - 2020', '2018 - 2020'), ('2021 - 2022', '2021 - 2022'), ('2023 to present', '2023 to present')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Pending Validation', 'Pending Validation'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=20),
        ),
    ]
