# Generated by Django 4.1.7 on 2024-05-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_listing_asking_price_listing_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='listings',
            field=models.ManyToManyField(blank=True, null=True, related_name='transactions', to='rest.listing'),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
