# Generated by Django 4.1.7 on 2024-04-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_listing_buy_date_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bike_condition',
            field=models.CharField(blank=True, choices=[('Needs some love', 'Needs some love'), ('Works well (201-500 Rides)', 'Works well (201-500 Rides)'), ('Very good (51-200 Rides)', 'Very good (51-200 Rides)'), ('Excellent (0 - 50 Rides)', 'Excellent (0 - 50 Rides)')], max_length=100, null=True),
        ),
    ]
