# Generated by Django 4.1.7 on 2024-11-17 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_customer_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Add', 'Add'), ('Withdraw', 'Withdraw')], default='Withdraw', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.customer')),
            ],
        ),
    ]
