# Generated by Django 4.1.7 on 2024-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_alter_transaction_listings_delete_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='listings',
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
