# Generated by Django 4.1.7 on 2024-05-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_alter_listing_bike_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='asking_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
