# Generated by Django 4.1.7 on 2024-05-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_remove_transaction_listings_transaction_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
