# Generated by Django 4.1.7 on 2024-09-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_remove_comment_listing_delete_file_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='customer/'),
        ),
    ]
