# Generated by Django 4.1.7 on 2024-05-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending PickUp', 'Pending PickUp'), ('Pending Delivery', 'Pending Delivery'), ('Delivered', 'Deliver'), ('Sold', 'Sold')], default='Approved', max_length=20),
        ),
    ]
