# Generated by Django 4.1.7 on 2024-09-03 14:48

from django.db import migrations, models
import rest.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default=0, upload_to=rest.models.Customer.get_upload_path),
            preserve_default=False,
        ),
    ]
