# Generated by Django 4.1.7 on 2024-05-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_listing_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending Pickup', 'Pending Pickup'), ('Pending Delivery', 'Pending Delivery'), ('Delivered', 'Delivered'), ('Sold', 'Sold')], default='Approved', max_length=20),
        ),
    ]
