# Generated by Django 4.1.7 on 2024-05-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_alter_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='ids/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending Pickup', 'Pending Pickup'), ('Pending Delivery', 'Pending Delivery'), ('Delivered', 'Deliver'), ('Sold', 'Sold')], default='Approved', max_length=20),
        ),
    ]
