# Generated by Django 4.1.7 on 2024-09-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_alter_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
