# Generated by Django 4.1.7 on 2024-09-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_listing_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='close_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Pending Confirmation', 'Pending Confirmation'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Closed', 'Closed'), ('Pending Payment', 'Pending Payment'), ('Sold', 'Sold')], default='Pending Confirmation', max_length=200),
        ),
    ]
