# Generated by Django 4.1.7 on 2024-05-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Payment Initiated', 'Payment Initiated'), ('Payment on Hold', 'Payment on Hold'), ('Payout Completed', 'Payout Completed')], default='Pending', max_length=20),
        ),
    ]
