# Generated by Django 4.1.7 on 2024-05-09 11:09

from django.db import migrations, models
import rest.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_listing_image_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=rest.models.customer_image_upload_path),
        ),
    ]
