# Generated by Django 4.1.7 on 2024-06-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='other_accessories',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='other_condition',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='serial_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
