# Generated by Django 4.1.7 on 2024-09-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_alter_customer_status_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='language',
            field=models.CharField(blank=True, default='EN', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Cars', 'Cars'), ('Motos', 'Motos'), ('Boats', 'Boats'), ('Smartphones and Tablets', 'Smartphones and Tablets'), ('Animals', 'Animals'), ('Tech', 'Tech'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Deco', 'Deco'), ('Art', 'Art'), ('Jewelry', 'Jewelry'), ('Sports', 'Sports'), ('Real Estate', 'Real Estate'), ('Agriculture', 'Agriculture'), ('Lifestyle', 'Lifestyle'), ('Apparel', 'Apparel'), ('Kids', 'Kids'), ('Gaming', 'Gaming')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
