# Generated by Django 4.1.7 on 2024-06-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_listing_location_zipcode_listing_queue_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='queue_order',
            field=models.CharField(blank=True, choices=[('TMS', 'TMS'), ('Promoted', 'Promoted'), ('Normal', 'Normal)')], max_length=100, null=True),
        ),
    ]
