# Generated by Django 4.1.7 on 2024-09-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_alter_customer_language_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Cars', 'Cars'), ('Motos', 'Motos'), ('Boats', 'Boats'), ('Tech', 'Tech'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Art & Deco', 'Art & Deco'), ('Jewelry', 'Jewelry'), ('Sports', 'Sports'), ('Real Estate', 'Real Estate'), ('Lifestyle', 'Lifestyle'), ('Apparel', 'Apparel'), ('Kids', 'Kids'), ('Gaming', 'Gaming')], max_length=100),
        ),
    ]
