# Generated by Django 4.1.7 on 2024-06-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_alter_listing_queue_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Pending Confirmation', 'Pending Confirmation'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending Pickup', 'Pending Pickup'), ('Pending Delivery', 'Pending Delivery'), ('Delivered', 'Delivered'), ('Sold', 'Sold')], default='Approved', max_length=20),
        ),
    ]
