# Generated by Django 4.1.7 on 2024-09-15 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='buyer_email',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buyer_phone_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='items',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller_email',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller_phone_number',
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='rest.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='listing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='rest.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='rest.customer'),
            preserve_default=False,
        ),
    ]
