# Generated by Django 4.1.7 on 2024-07-11 21:26

from django.db import migrations, models
import rest.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_alter_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=rest.models.customer_image_upload_path),
        ),
    ]
