# Generated by Django 4.1.7 on 2024-09-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_transaction_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Payment Initiated', 'Payment Initiated'), ('Payment on Hold', 'Payment on Hold'), ('Payout Completed', 'Payout Completed'), ('Waiting Payment/Delivery', 'Waiting Payment/Delivery'), ('Payment Confirmed', 'Payment Confirmed'), ('Delivery Confirmed', 'Delivery Confirmed'), ('Transaction completed', 'Transaction Completed'), ('Transaction on Dispute', 'Transaction on Dispute')], default='Pending', max_length=200),
        ),
    ]
