# Generated by Django 4.1.7 on 2024-09-16 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Waiting Payment/Delivery', 'Waiting Payment/Delivery'), ('Payment Confirmed', 'Payment Confirmed'), ('Delivery Confirmed', 'Delivery Confirmed'), ('Transaction completed', 'Transaction Completed'), ('Transaction on Dispute', 'Transaction on Dispute')], default='Waiting Payment/Delivery', max_length=200),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Dispute Initiated', 'Dispute Initiated'), ('Dispute in Analysis', 'Dispute in Analysis'), ('Resolved for Buyer', 'Resolved for Buyer'), ('Resolved for Seller', 'Resolved for Seller')], default='Dispute Initiated', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_disputed', to='rest.customer')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_disputed', to='rest.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_disputed', to='rest.customer')),
            ],
        ),
    ]
