# Generated by Django 4.1.7 on 2024-07-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_customer_address1_customer_address2_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
