# Generated by Django 4.1.7 on 2024-07-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_customer_vat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customer',
            name='valid_id',
            field=models.BooleanField(default=False),
        ),
    ]
