# Generated by Django 4.1.7 on 2024-09-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_alter_transaction_status_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
