# Generated by Django 4.1.7 on 2024-09-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0017_transaction_delivered_transaction_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Pending Confirmation', 'Pending Confirmation'), ('Active', 'Active'), ('Rejected', 'Rejected'), ('Closed', 'Closed'), ('On hold', 'On hold'), ('Pending Payment', 'Pending Payment'), ('Sold', 'Sold')], default='Active', max_length=200),
        ),
    ]
