# Generated by Django 4.1.7 on 2024-09-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0018_alter_listing_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='balance',
            new_name='free_deposit',
        ),
        migrations.AddField(
            model_name='customer',
            name='frozen_deposit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
