# Generated by Django 4.1.7 on 2024-07-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0018_remove_customer_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
