# Generated by Django 4.1.7 on 2024-09-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0019_rename_balance_customer_free_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='trusted_buyer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='trusted_seller',
        ),
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Grass', 'Grass')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='level',
            field=models.IntegerField(blank=True, choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Grass', 'Grass')], max_length=20, null=True),
        ),
    ]
