# Generated by Django 4.1.7 on 2024-09-23 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0020_remove_customer_trusted_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='transaction_number',
        ),
        migrations.AddField(
            model_name='dispute',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='rest.transaction'),
            preserve_default=False,
        ),
    ]
