# Generated by Django 4.1.7 on 2024-07-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0020_rename_model_listing_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='images',
        ),
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.ManyToManyField(blank=True, to='rest.file'),
        ),
    ]
