# Generated by Django 4.1.7 on 2024-07-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0021_file_remove_listing_images_listing_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='asking_price',
            new_name='buynow_price',
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='excerpt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='promoted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location_address1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
