# Generated by Django 4.1.7 on 2024-09-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0021_remove_dispute_transaction_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='listing',
        ),
        migrations.AddField(
            model_name='dispute',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='persona',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
