# Generated by Django 4.1.7 on 2024-09-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0022_remove_dispute_listing_dispute_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Waiting Payment/Delivery', 'Waiting Payment/Delivery'), ('Transaction completed', 'Transaction Completed'), ('Transaction on Dispute', 'Transaction on Dispute'), ('Transaction Canceled', 'Transaction Canceled')], default='Waiting Payment/Delivery', max_length=200),
        ),
    ]
