# Generated by Django 4.1.7 on 2024-10-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0023_alter_customer_currency_alter_customer_language_and_more'),
        ('rest', '0023_alter_transaction_status'),
    ]

    operations = [
    ]
