# Generated by Django 4.1.7 on 2024-10-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0023_alter_customer_currency_alter_customer_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
