# Generated by Django 5.1 on 2024-08-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0023_listing_level_listing_slug_alter_listing_status_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
