# Generated by Django 5.1 on 2024-08-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0024_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Active', max_length=20),
        ),
    ]
