# Generated by Django 5.1 on 2024-08-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0025_bid_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='buyer_stars',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='seller_stars',
        ),
    ]
